### PR TITLE
Laravel 6.0 Shift

### PR DESCRIPTION
**Pull request by driesvints**
This pull request includes the changes for upgrading to Laravel 6.0. Feel free to commit any additional changes to the `shift-19284` branch.

**Before merging**, you need to:

- Checkout the `shift-19284` branch
- Review **all** pull request comments for additional changes
- Update your dependencies for Laravel 6.0
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Thoroughly test your application ([no tests?](https://confidentlaravel.com))

If you need help with your upgrade, check out the [Human Shifts](https://laravelshift.com/human-shifts). You may also join the [Shifty Coders](https://laravelshift.com/shifty-coders) Slack workspace to level-up your Laravel skills.

### CODE REVIEW

**Comment by driesvints** [comment]
:warning: Shift defaulted the following configuration files. This was done in the [Default config files](https://github.com/laravelio/portal/pull/443/commits/9685ff0449cdd749102f124cd5e87fba31239a39?w=1) commit so you may easily review and backfill your customizations. If you have a lot of customizations, you may also undo this commit with `git revert` and upgrade these files manually.

- [ ] config/database.php
- [ ] config/logging.php
- [ ] config/mail.php
- [ ] config/services.php

**Comment by driesvints** [comment]
:information_source: Laravel 6.0 changed the default Redis client from `predis` to `phpredis`. You may keep using `predis` by setting `REDIS_CLIENT=predis` for your environment.

However, if possible, consider switching to [phpredis](https://github.com/phpredis/phpredis) to gain the performance of its PHP extension and avoid using the deprecated `predis` dependency which will be removed in Laravel 7.0.

**Comment by driesvints** [comment]
:information_source: Shift makes an effort to [update your dependencies](https://github.com/laravelio/portal/pull/443/commits/f8b31ddd5895e072d54a691ab71dabbab710cad6?w=1) for Laravel 6.0. While many of the popular packages are reviewed, you may have to update additional packages or version constraints in order for your application to be compatible with Laravel 6.0. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by driesvints** [comment]
:information_source: The Eloquent model's `toArray()` method will now cast any attributes that implement `Illuminate\Contracts\Support\Arrayable` to an array. While unlikely to impact your application, this change could effect code which relies upon the previous data type or output.

**Comment by driesvints** [comment]
:warning: Previous versions of Laravel would bind parameters passed to the `route()` helper as placeholder values even if the names mismatched. In Laravel 6.0, named parameters not matching placeholders are attached to the query string instead.

Shift detected the following `route()` calls passing named parameters you should review to ensure these match the route placeholder name.

- [ ] app/User.php

**Comment by driesvints** [comment]
:information_source: Laravel 6.0 made [performance optimizations](https://github.com/laravel/framework/pull/28153) for _integer_ key types. If you are using a _string_ as your model's primary key, you may set the `$keyType` property on your model.

```php
/**
 * The "type" of the primary key ID.
 *
 * @var string
 */
protected $keyType = 'string';
```

**Comment by driesvints** [comment]
:information_source: The `mandrill` and `sparkpost` mail drivers, as well as the `rackspace` storage driver were removed in Laravel 6.0. If you were using these drivers, you may adopt a community maintained package which provides the driver.

**Comment by driesvints** [comment]
:information_source: Previous versions of Laravel would retry jobs indefinitely. Beginning with Laravel 6.0, the `php artisan queue:work` now tries a job **one time by default**. If you want to force jobs to be tried indefinitely, you may pass the `--tries=0` option.

**Comment by driesvints** [comment]
:tada: Congratulations, you're now running the latest version of Laravel.

The following _Shifts_ can ensure your app is fully upgraded and following the practices recommended by Laravel and the community:
- [Laravel Linter](https://laravelshift.com/opinionated-laravel-way-shift) analyzes your codebase for potential opportunities to do things "The Laravel Way".
- [Laravel Fixer](https://laravelshift.com/laravel-code-fixer) automates many of the suggestions found by the _Linter_ and other _Shifts_.
- [Upgrade Checker](https://laravelshift.com/laravel-upgrade-checker) ensures your application is fully upgraded by detecting any outdated code.

In addition, stay upgraded forever as well as run these _Shifts_ by subscribing to one of the new [Shifty Plans](https://laravelshift.com/shifty-plans).

**Comment by joedixon** [comment]
> ℹ️ The `mandrill` and `sparkpost` mail drivers, as well as the `rackspace` storage driver were removed in Laravel 6.0. If you were using these drivers, you may adopt a community maintained package which provides the driver.

Assuming we are using Mailgun in production @driesvints?

**Comment by driesvints** [comment]
@joedixon we use Sparkpost. I'll have to migrate it to Mailgun first.

**Pull request merged**
