### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by LucasLeandro1204**
I'm working on the notifications, we need that to #271,  #270 and #279. But I'm not a good designer, so I need help before getting deep into it xd

It's using vue, he will turn the job easier later.

This is how it looks now

image

The first one are in the hover state, the last one are marked as read.

### CODE REVIEW

**Comment by driesvints** [comment]
This is amazing! I'll try to look at this as soon as I have the time.

**Comment by atgg** [comment]
> It's using vue, he will turn the job easier later.

Any reason to use Vue instead of traditional server-side rendering?

**Comment by LucasLeandro1204** [comment]
@atgg It's not that necessary, however is easier to manipulate the dom and make ajax requests with it, thinking about the "mark as read" and "delete" triggers, and later will be easier to add real time notifications.
 
But what is better, that page or a modal?
reference: 

image

**Comment by atgg** [comment]
@LucasLeandro1204

> however is easier to manipulate the dom [...] thinking about the "mark as read" and "delete" triggers

I think it would be better to mark every notification as read just by visiting the notifications page. Also, I have mixed feelings about being able to delete a notification.

> But what is better, that page or a modal?

I would go for the page just because it's possible for users who refuse to run JavaScript to see the notifications.

**Comment by LucasLeandro1204** [comment]
@atgg 
> I think it would be better to mark every notification as read after rendering the notifications page.

Yeah, it's good to, so I will add an aside menu like github.

**Comment by driesvints** [comment]
@LucasLeandro1204 modal looks nicer.

I personally think it's best to let the user manually mark notifications as read like Github does.

**Comment by driesvints** [comment]
@LucasLeandro1204 actually I think both the modal and screen can be useful. Perhaps a "view all" button at the bottom of the modal?

**Comment by LucasLeandro1204** [comment]
@driesvints I agree, both are great. The modal will show only unread notifications.

**Comment by LucasLeandro1204** [comment]
@driesvints I downsized the sizes to match the modal

image

That's how the modal looks like (ignore the read notifications).

image

When empty

image

I used the same header background color in notification hover, but seems too dark for me, and the "view all" button aren't the best too.

To mobile I think it's better to hide the modal and link the button to /notifications, what you say?

**Comment by LucasLeandro1204** [comment]
Added a small toggler to subscribe a Thread.

image

**Comment by driesvints** [comment]
@LucasLeandro1204 I think it's best that we do that in another PR so this one doesn't becomes to large. I also had something else in mind for that. Just a subscribe/unsubscribe button on the left.

**Comment by LucasLeandro1204** [comment]
@driesvints I added it here to have something to test the notifications in hand, but I can split it into another pull request to this branch.

**Comment by driesvints** [comment]
@LucasLeandro1204 heya, unfortunately I won't have time to look at this until next week. I'll keep you posted.

**Comment by LucasLeandro1204** [comment]
@driesvints I guess you already can review this pull request, feel free to when you have time =)

**Comment by driesvints** [comment]
@LucasLeandro1204 heya! So sorry I haven't gotten to this yet. It's been pretty hectic for me lately and I still have quite a busy month ahead so it might be a while before I get to this. But I haven't forgotten about it yet, just so you know :)

I saw that you closed your other PR? Any reason for that?

**Comment by LucasLeandro1204** [comment]
@driesvints It's a bit messy (all the commits from here are there) and unfinished, I will let it closed until we finish this one.

**Comment by inesarmadabras** [comment]
Hi @LucasLeandro1204 ! Any news on this pull request? Anything missing or just waiting for review?

**Comment by driesvints** [comment]
@inesarmadabras waiting for review from me.

**Comment by LucasLeandro1204** [comment]
@inesarmadabras I have to review this one again, probably some rework, is already too old xd.

**Comment by BobbyBorisov** [comment]
@LucasLeandro1204 these notifications look so cool! 🥇

**Comment by driesvints** [comment]
Hey @LucasLeandro1204. I'm gonna close this for now since the PR is out of date with the current codebase. Maybe we can salvage some things in the future on a fresh attempt. Thanks for your work and sorry for getting back so late.

**Pull request closed without merging**
