### PR TITLE
Thread Subscriptions

### PR DESCRIPTION
**Pull request by driesvints**
Implementation for #270. This is all still very much WIP.

Can later on perhaps be used in #290 and #310.

### CODE REVIEW

**Comment by m1guelpf** [comment]
@driesvints As another use case, maybe subscribe users that comment to the thread?

**Comment by driesvints** [comment]
@m1guelpf yeah that's the idea. It's not very clear in the user stories above, that's true. I'll update it soon.

**Comment by driesvints** [comment]
@m1guelpf moved the user stories to the issue and added some more to clarify the replying.

**Comment by BobbyBorisov** [comment]
hey @driesvints i am currently hunting for open source laravel project in order to boost my knowledge and see good practices, and so far i can say that this is the first project that i found with tests 🎉  . I don't know if its the write place to write or not but forgive me if its not. I reviewed most of the code and i see you are using command/jobs pattern and i was wondering why you chose it? Cheers!

**Comment by driesvints** [comment]
@BobbyBorisov heya, no problem! I already answered that question in an issue so I'm going to link to that: https://github.com/laravelio/portal/issues/244

Hope that explains 🙂

**Pull request merged**
