### PR TITLE
Failing test for mentioned users bug

### PR DESCRIPTION
**Pull request by driesvints**
This PR contains a failing test for #866. Still in search of a soltion. Most likely the regex in the MarkdownServiceProvider needs to be tweaked.

### CODE REVIEW

**Comment by driesvints** [comment]
@joelclermont wow that was super helpful! I think it's best to escalate this to the commonmark repo so I opened an issue on it: https://github.com/thephpleague/commonmark/issues/882

Thanks! 👏

**Comment by joelclermont** [comment]
Reading through the suggested workarounds on the CommonMark issue, I was thinking that removing HTML parsing is probably the right approach. I'm not sure we even need the `HtmlInlineParser` since we're already escaping everything.

If you agree, I'd be willing to put together a PR for that. Or let me know if you have another approach in mind.

**Comment by driesvints** [comment]
Hmm, don't think we want to go down the road to remove HTML parsing. We still want to render a tags, etc. Also, all existing posts would be affected this way.

**Comment by driesvints** [comment]
Thanks @joelclermont for the investigation 👍

**Pull request merged**
