### PR TITLE
The Next Version

### PR DESCRIPTION
**Pull request by driesvints**
It's been quite a ride but the next version is finally here. I've worked hard on this over the past months (and years), working on it during free moments, evenings and vacations. That's why it went so slow and why it took so long for me to send this in. In the beginning I wanted to release a much more feature-rich next version but in the end I decided to cut out a lot of to-be features to finally launch this next version. After this PR is merged I'll start by adding issue for ideas and features that can be worked on and we'll go from there. I'm looking forward to seeing contributions from the community.

This PR will remain open for ~2 weeks. After that I'm merging it and launching the next version. From there on out the road lies open to extend & improve the platform. I'll write a more extensive blog post once the new version is released about how I want to continue with Laravel.io.

Thank you for taking the time to read this and being this patient for me to send this in. I know it's a long time coming but from here on I hope we can continue together.

## The Next Version tl;dr

Let me start off by pointing out the obvious: I'm not a designer. By no means the next version looks like the way I want Laravel.io to be in the future. I'm hoping the community can help me with this so we can make Laravel.io look much better in the near future. We're currently using the [Flatly theme](https://bootswatch.com/flatly/) for Bootstrap 3 but I'm all open to look at other options. We'll also be making the upgrade to Bootstrap 4 as soon as a stable version drops.

The next version comes with all the features you know from the current portal site. You can post forum threads, reply to them and mark solution replies. User profiles got a new coat of paint as well as the user settings screen. One of the new things added is a user dashboard. I hope that this screen can be extended in the future to provide more meaningful info. Forum threads also got a bunch of new tags which were sorely needed.

## How you can help

At the moment the best way you can help is to install the next version and test things out. Report things that aren't clear, missing or broken. Please refrain from requesting large features for the next version. I know notifications are ranked very high on everyone's wishlist and we'll get to that but until the next version is merged I want to concentrate on finishing up this PR first.

When you find things that can improve you're free to send in a PR to the develop branch. If it's approved, we'll merge it in so it's included for the next release.

### CODE REVIEW

**Comment by RobinMalfait** [comment]
I've noticed a design issue when hovering over the tags:

**Comment by MichaelDeBoey** [comment]
Nice work @driesvints! 🙂
Almost one year since the first commit, that's real dedication to the community 😉
Thanks for that! 🎉 

Everything looks great, couldn't fine anything on the first look

**Comment by driesvints** [comment]
@MichaelDeBoey thanks! I rebased a couple of times which messes with the dates but it's actually been in development a lot longer :)

**Comment by MichaelDeBoey** [comment]
@driesvints Where do you want your statue to be build? 😉

**Comment by introwit** [comment]
**How about changing the following**

lio1

**To this**

lio2

-----

4 blocks line by line seems overwhelming, this looks light to eyes and delivers better UX

**Comment by driesvints** [comment]
@introwit I agree. Feel free to make the PR, otherwise I'll update this soon.

**Comment by introwit** [comment]
@driesvints saw your confirmation on twitter that local copy worked in a fresh Homestead install for you, but I am still getting errors while yarn install & dev. Will destroy and try again so that I can send in the PR.

**Comment by driesvints** [comment]
@RobinMalfait decided not to put too much effort into fixing that styling issue. You're free to send in a PR if you really want to.

@introwit changed the link and removed the signup link (it's in the nav anyway). Let me know what you think. https://beta.laravel.io/login

**Pull request merged**
